#!/usr/bin/env bash
# sync-memory.sh — mirror Cowork auto-memory into a project-local snapshot.
#
# The canonical, *live* memory used during Cowork sessions lives outside the
# project workspace at:
#
#     /sessions/<session-id>/mnt/.auto-memory/
#
# That path is sandbox-local and disappears between sessions / outside Cowork.
# To make the memory travel with the repo, we mirror it into ./memory/ and
# commit the snapshot. Run this script before committing whenever you've
# updated memory in a session.
#
# Usage:
#   scripts/sync-memory.sh                     # default: .auto-memory -> memory
#   scripts/sync-memory.sh <src> <dst>         # explicit override
#   scripts/sync-memory.sh --check             # exit non-zero if drift exists
#
# Notes:
# - Only *.md files are copied. The index (MEMORY.md) and entry files all use
#   the .md suffix; anything else in .auto-memory is ignored.
# - --delete: if a memory file was removed upstream, remove it from the snapshot.
# - This script is idempotent. Running it twice with no upstream changes is a
#   no-op.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"

SRC_DEFAULT="$REPO_ROOT/.auto-memory"
DST_DEFAULT="$REPO_ROOT/memory"

CHECK_ONLY=0
if [[ "${1:-}" == "--check" ]]; then
  CHECK_ONLY=1
  shift
fi

SRC="${1:-$SRC_DEFAULT}"
DST="${2:-$DST_DEFAULT}"

if [[ ! -e "$SRC" ]]; then
  echo "sync-memory: source not found: $SRC" >&2
  echo "  (expected the .auto-memory symlink at the repo root, or an explicit src arg)" >&2
  exit 2
fi

# Resolve through the symlink so rsync sees the real directory.
SRC_RESOLVED="$(cd "$SRC" && pwd -P)"

if [[ ! -d "$SRC_RESOLVED" ]]; then
  echo "sync-memory: source resolved to a non-directory: $SRC_RESOLVED" >&2
  exit 2
fi

mkdir -p "$DST"

if (( CHECK_ONLY )); then
  # Dry-run: print what would change, exit non-zero if anything would change.
  # Filter rsync's noise: ignore the bare "./" entry (mtime on the dir itself)
  # and SNAPSHOT.md (locally generated, never copied from source).
  CHANGES="$(rsync -a --delete --dry-run --itemize-changes \
              --exclude='SNAPSHOT.md' \
              --include='*.md' --exclude='*' \
              "$SRC_RESOLVED/" "$DST/" \
              | grep -v -E '^\.d[\.\?]+ \./$' || true)"
  if [[ -n "$CHANGES" ]]; then
    echo "sync-memory: snapshot is out of date. The following would change:"
    echo "$CHANGES"
    exit 1
  fi
  echo "sync-memory: snapshot is up to date."
  exit 0
fi

# Real sync.
rsync -a --delete \
  --exclude='SNAPSHOT.md' \
  --include='*.md' --exclude='*' \
  "$SRC_RESOLVED/" "$DST/"

# Stamp a marker so it's obvious where the snapshot came from and when.
{
  echo "# memory snapshot"
  echo ""
  echo "Generated by \`scripts/sync-memory.sh\` on $(date -u +%Y-%m-%dT%H:%M:%SZ)."
  echo "Source: \`$SRC_RESOLVED\` (canonical Cowork auto-memory path)."
  echo ""
  echo "The live, mutable copy lives outside the repo. Files here are a snapshot"
  echo "for portability and version history. To refresh, run:"
  echo ""
  echo '    scripts/sync-memory.sh'
  echo ""
  echo "To check for drift in CI or pre-commit, run:"
  echo ""
  echo '    scripts/sync-memory.sh --check'
} > "$DST/SNAPSHOT.md"

COUNT="$(find "$DST" -maxdepth 1 -name '*.md' ! -name 'SNAPSHOT.md' | wc -l | tr -d ' ')"
echo "sync-memory: synced $COUNT memory file(s) from $SRC_RESOLVED -> $DST"
